### ISSUE TITLE
No Link to Dataset in Project Proposal

### ISSUE THREAD

**Issue by nickmccarty** [danishalib/Car-Price-Predicton-Using-Linear-Regression#1]
Hi Dan! 👋

Thank you for submitting your proposal. For the sake of communicating efficiently, I will be raising any relevant issues here -- and I'd suggest you do the same as they arise (given that I am a collaborator on your repo).

I very much enjoyed reading your proposal. In that vein, I'm particularly interested in taking a look at the data source(s) you're exploring.

**_Please provide a link in your README and/or in a comment here so that I can take a look_**, when you get the chance 👀

Thanks again for all of your efforts! I look forward to seeing what you put together 😃

**Comment by danishalib** [comment]
Hi Nick,
I hope you had fun holidays! The link to data set is given below... 

https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?resource=download&select=car+data.csv

**Comment by nickmccarty** [comment]
Hi Dan!

Thanks a bunch, I hope you had a fun break too 🤞

I'll go ahead and close this issue now -- thanks again, and have a great day! 😄
